#!/bin/bash
# Install versions of doxygen
arg0="${0##*/}"

# Space-serated list of doxygen versions to install if they're not already installed.
: ${DOXYGEN_VERSIONS:="1.8.1 1.8.2 1.8.3 1.8.4 1.8.5 1.8.6 1.8.7 1.8.8 1.8.9 1.8.10"}

# Directory where we build stuff. Using a local directory instead of NFS will speed things up.
: ${TEMPDIR:="$HOME/junk"}

# RMC toolchain directory where doxygen will be installed.
: ${TOOLCHAIN:="$RMC_RMC_TOOLCHAIN"}
: ${TOOLCHAIN:="$HOME/GS-CAD"}

# If non-empty, then re-install doxygen even if it seems to already be installed.
: REINSTALL

# Download source tarball into current working directory
get_source() {
    local version="$1" destination="$2"
    if [ ! -f "$HOME/Downloads/doxygen-$version.src.tar.gz" ]; then
	wget -O "$HOME/Downloads/doxygen-$version.src.tar.gz" \
	    "ftp://ftp.stack.nl/pub/users/dimitri/doxygen-$version.src.tar.gz"
    fi
    ln -sf "$HOME/Downloads/doxygen-$version.src.tar.gz" "$destination"
}

is_installed() {
    local prefix="$1"
    local bin="$prefix/bin/doxygen"
    if [ ! -x "$bin" ]; then
	echo "$arg0: failed to install (missing $bin)" >&2
	return 1
    fi
    return 0
}

for doxygen_version in $DOXYGEN_VERSIONS; do
    (figlet -c "$doxygen_version" || banner "$doxygen_version") 2>/dev/null

    eval $(rmc clear)
    export RMC_RMC_TOOLCHAIN="$TOOLCHAIN"
    eval $(rmc resolve parallelism)
    eval $(RMC_DOXYGEN_VERSION="$doxygen_version" rmc resolve doxygen)

    logfile="doxygen-$doxygen_version.log"
    date >"$logfile"
    echo "doxygen-$doxygen_version for $RMC_DOXYGEN_VERSION"
    echo "doxygen root directory is $RMC_DOXYGEN_ROOT"
    echo "log file is " $(rmc realpath "$logfile")
    if [ "$REINSTALL" != "" ]; then
	: install even if it appears to be installed
    elif is_installed "$RMC_DOXYGEN_ROOT" 2>/dev/null; then
	echo "already installed; skipping"
	echo "already installed; skipping" >>"$logfile"
	continue
    fi

    temporary_prefix="$RMC_DOXYGEN_ROOT-$(date '+%Y%m%d')"

    mkdir -p "$TEMPDIR"
    (
	cd "$TEMPDIR" || exit 1

	echo "downloading doxygen-$doxygen_version..." >&2
	tarball="doxygen-$doxygen_version.src.tar.gz"
	get_source "$doxygen_version" "$tarball"
	if [ ! -f "$tarball" ]; then
	    echo "$arg0: couldn't download $tarball" >&2
	else
	    builddir="doxygen-$doxygen_version"
	    echo "unpacking into $builddir..." >&2
	    rm -rf "$builddir"
	    tar xf "$tarball" || exit 1
	    if [ ! -d "$builddir" ]; then
		echo "$arg0: unpacking failed for $tarball into $builddir" >&2
	    elif [ -r "$builddir/CMakeLists.txt" ]; then
		mkdir "$builddir/_build" || exit 1
		cd "$builddir/_build" || exit 1

		eval $(RMC_BUILD_SYSTEM=cmake RMC_CMAKE_VERSION=system rmc resolve --require cmake)
		"$RMC_CMAKE_FILE" .. -DCMAKE_INSTALL_PREFIX="$temporary_prefix" -Dbuild_search=YES

		make -j$RMC_PARALLELISM || exit 1
		make install || exit 1
		is_installed "$temporary_prefix" || exit 1
	    elif [ -r "$builddir/configure" ]; then
		cd "$builddir" || exit 1
		./configure --prefix "$temporary_prefix" || exit 1
		make -j$RMC_PARALLELISM || exit 1
		make install || exit 1
	    else
		echo "don't know how to build this version of doxygen" >&2
		exit 1
	    fi

	    # Remove previous installation if any (only need to do this if the old installation is a directory rather
	    # than a symlink.
	    if [ ! -h "$RMC_DOXYGEN_ROOT" -a -d "$RMC_DOXYGEN_ROOT" ]; then
		rm -rf "$RMC_DOXYGEN_ROOT.bak"
		mv "$RMC_DOXYGEN_ROOT" "$RMC_DOXYGEN_ROOT.bak"
	    else
		rm -f "$RMC_DOXYGEN_ROOT"
	    fi

	    # Link in the new installation. The "-r" switch of "ln" is not always available, so do it the hard way.
	    if false; then
		ln -sfr "$temporary_prefix" "$RMC_DOXYGEN_ROOT"
	    else
		temporary_base=$(basename "$temporary_prefix")
		real_base=$(basename "$RMC_DOXYGEN_ROOT")
		dir="${temporary_prefix%/$temporary_base}"
		(cd "$dir" && ln -sf "$temporary_base" "$real_base")
	    fi
	    is_installed "$RMC_DOXYGEN_ROOT" || exit 1
	    
	fi
    ) |tee -a "$logfile"
    mv "$logfile" "$RMC_DOXYGEN_ROOT/installation.log"
done
