#!/bin/bash

eval $(RMC_DOXYGEN_VERSION=arbitrary rmc resolve doxygen)

if [ "$RMC_DOXYGEN_BASEDIR" = "" ]; then
    echo "$arg0: doxygen base directory is not specified" >&2
    exit 1
fi

if [ ! -d "$RMC_DOXYGEN_BASEDIR" ]; then
    echo "$arg0: doxygen base directory does not exist: $RMC_DOXYGEN_BASEDIR" >&2
    exit 1
fi

for dir in $(cd "$RMC_DOXYGEN_BASEDIR" && find . -follow -maxdepth 3 -name doxygen -type f -perm -100 |sort); do
    version=$(echo "$dir" |cut -d/ -f2)
    echo "doxygen='$version'"
done
