#!/bin/bash

RMC_YAML_BASEDIR=$HOME/GS-CAD/yaml


if [ "$RMC_YAML_BASEDIR" = "" ]; then
    echo "$arg0: yaml base directory is not specified" >&2
    exit 1
fi

if [ ! -d "$RMC_YAML_BASEDIR" ]; then
    echo "$arg0: yaml base directory does not exist: $RMC_YAML_BASEDIR" >&2
    exit 1
fi

for dir in $(cd "$RMC_YAML_BASEDIR" && find . -follow -maxdepth 6 -name yaml.h |sort); do
    version=$(echo "$dir" |cut -d/ -f2)
    boost=$(echo "$dir" |cut -d/ -f3 |cut -d- -f2-)
    compiler=$(echo "$dir" |cut -d/ -f4)
    echo "yaml='$version' boost='$boost' compiler='$compiler'"
done
