#!/bin/bash

RMC_WT_BASEDIR=$HOME/GS-CAD/wt


if [ "$RMC_WT_BASEDIR" = "" ]; then
    echo "$arg0: wt base directory is not specified" >&2
    exit 1
fi

if [ ! -d "$RMC_WT_BASEDIR" ]; then
    echo "$arg0: wt base directory does not exist: $RMC_WT_BASEDIR" >&2
    exit 1
fi

for dir in $(cd "$RMC_WT_BASEDIR" && find . -follow -maxdepth 6 -name WConfig.h |sort); do
    version=$(echo "$dir" |cut -d/ -f2)
    boost=$(echo "$dir" |cut -d/ -f3 |cut -d- -f2-)
    compiler=$(echo "$dir" |cut -d/ -f4)
    echo "wt='$version' boost='$boost' compiler='$compiler'"
done
