#!/bin/bash

eval $(RMC_BOOST_VERSION=arbitrary rmc resolve boost)

if [ "$RMC_BOOST_BASEDIR" = "" ]; then
    echo "$arg0: boost base directory is not specified" >&2
    exit 1
fi

if [ ! -d "$RMC_BOOST_BASEDIR" ]; then
    echo "$arg0: boost base directory does not exist: $RMC_BOOST_BASEDIR" >&2
    exit 1
fi

for dir in $(cd "$RMC_BOOST_BASEDIR" && find . -follow -maxdepth 3 -name lib -type d |sort); do
    version=$(echo "$dir" |cut -d/ -f2)
    compiler=$(echo "$dir" |cut -d/ -f3)
    echo "boost='$version' compiler='$compiler'"
done
