#!/bin/bash

eval $(RMC_DLIB_VERSION=arbitrary rmc resolve dlib)

if [ "$RMC_DLIB_BASEDIR" = "" ]; then
    echo "$arg0: dlib base directory is not specified" >&2
    exit 1
fi

if [ ! -d "$RMC_DLIB_BASEDIR" ]; then
    echo "$arg0: dlib base directory does not exist: $RMC_DLIB_BASEDIR" >&2
    exit 1
fi

for dir in $(cd "$RMC_DLIB_BASEDIR" && find . -follow -maxdepth 3 -name revision.h -type f |sort); do
    version=$(echo "$dir" |cut -d/ -f2)
    echo "dlib='$version'"
done
