#!/bin/bash

eval $(RMC_CMAKE_VERSION=arbitrary rmc resolve cmake)

if [ "$RMC_CMAKE_BASEDIR" = "" ]; then
    echo "$arg0: cmake base directory is not specified" >&2
    exit 1
fi

if [ ! -d "$RMC_CMAKE_BASEDIR" ]; then
    echo "$arg0: cmake base directory does not exist: $RMC_CMAKE_BASEDIR" >&2
    exit 1
fi

for dir in $(cd "$RMC_CMAKE_BASEDIR" && find . -follow -maxdepth 3 -name cmake -type f -perm -100 |sort); do
    version=$(echo "$dir" |cut -d/ -f2)
    echo "cmake='$version'"
done
