#!/bin/bash

eval $(RMC_READLINE_VERSION=arbitrary rmc resolve readline)

if [ "$RMC_READLINE_BASEDIR" = "" ]; then
    echo "$arg0: readline base directory is not specified" >&2
    exit 1
fi

if [ ! -d "$RMC_READLINE_BASEDIR" ]; then
    echo "$arg0: readline base directory does not exist: $RMC_READLINE_BASEDIR" >&2
    exit 1
fi

for dir in $(cd "$RMC_READLINE_BASEDIR" && find . -follow -maxdepth 4 -name readline.h -type f |sort); do
    version=$(echo "$dir" |cut -d/ -f2)
    echo "readline='$version'"
done
