#!/bin/bash
# Search the source source tree for a particular pattern.
# Usage:
#   rg-search C-CODE

top_srcdir="$(git rev-parse --show-cdup)" || exit 1
git ls-tree -r --name-only --full-tree -z HEAD |xargs -0 -n1 -I{} $HOME/sawyer/_build/tools/searchCode "$@" $top_srcdir{}
