#!/bin/bash
#
# Echos the name of the source directory that corresponds to the current working directory in the build tree, which is really
# useful when you're sitting in the build tree and want to see something in the source tree:
#
#     ls $(rosegit-src)
#     ln -s $(rosegit-src)/*.bin .

cwd=$(rmc realpath .)
bld=$(rmc realpath "$ROSE_BUILD")
src=$(rmc realpath "$ROSE_SOURCE")

base="${cwd#$bld/}"

echo "$src/$base"
